import { Product } from './types';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Classic Cloud9 T-Shirt',
    description: 'Premium quality cotton t-shirt with Cloud9 logo. Perfect for everyday wear.',
    price: 29.99,
    category: 'tshirts',
    image: 'https://via.placeholder.com/500x500?text=Cloud9+T-Shirt',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Navy', 'Gray'],
    stock: 50,
    rating: 4.8,
    reviews: 124,
    featured: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Urban Streetwear Shorts',
    description: 'Comfortable and stylish shorts for urban lifestyle. Available in multiple colors.',
    price: 39.99,
    category: 'shorts',
    image: 'https://via.placeholder.com/500x500?text=Cloud9+Shorts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Khaki', 'Gray'],
    stock: 35,
    rating: 4.6,
    reviews: 89,
    featured: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'Premium Canvas Sneakers',
    description: 'High-quality canvas sneakers with superior comfort. Perfect for any occasion.',
    price: 79.99,
    category: 'shoes',
    image: 'https://via.placeholder.com/500x500?text=Cloud9+Sneakers',
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    colors: ['Black', 'White', 'Navy', 'Red'],
    stock: 25,
    rating: 4.9,
    reviews: 156,
    featured: true,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    name: 'Oversized Cloud9 Tee',
    description: 'Trendy oversized t-shirt perfect for a relaxed, contemporary look.',
    price: 34.99,
    category: 'tshirts',
    image: 'https://via.placeholder.com/500x500?text=Oversized+Tee',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Cream', 'Olive'],
    stock: 40,
    rating: 4.7,
    reviews: 98,
    featured: false,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    name: 'Athletic Performance Shorts',
    description: 'Lightweight shorts designed for athletic performance and comfort.',
    price: 44.99,
    category: 'shorts',
    image: 'https://via.placeholder.com/500x500?text=Athletic+Shorts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Gray', 'Forest Green'],
    stock: 30,
    rating: 4.5,
    reviews: 67,
    featured: false,
    createdAt: new Date('2024-02-05'),
  },
  {
    id: '6',
    name: 'Classic High-Top Sneakers',
    description: 'Timeless high-top sneakers with ankle support and premium materials.',
    price: 89.99,
    category: 'shoes',
    image: 'https://via.placeholder.com/500x500?text=High-Top+Sneakers',
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    colors: ['Black', 'White', 'Brown', 'Navy'],
    stock: 20,
    rating: 4.8,
    reviews: 142,
    featured: false,
    createdAt: new Date('2024-02-10'),
  },
];

export const FEATURED_PRODUCTS = SAMPLE_PRODUCTS.filter(p => p.featured);
